### ISSUE TITLE
Update docs to access database from ec2 bastion host

### ISSUE THREAD

**Issue by AgusPk** [nanlabs/terraform-aws-starter#11]
### Describe the issue

The current documentation segment "Connecting to the Database" of the directory `live/core` is outdated and might generate confusions, we should update the correct variable names an proper steps to achieve the connection between the bastion host and the RDS instance

### Links

https://github.com/nanlabs/terraform-aws-starter/tree/main/live/core

**Comment by ulises-jeremias** [comment]
It is up to date now!
