### ISSUE TITLE
When running the existing example under live/core, Error creating in VPC endpoint

### ISSUE THREAD

**Issue by synthKyel** [nanlabs/terraform-aws-starter#18]
### Describe the bug

When run for the first time with the default configuration. It fails creating a secrets manager linked to the VPC

### Expected Behavior

Be able to attach secrets manager to the VPC endpoint

### Current Behavior

throws an error with this message

```
 Error: creating EC2 VPC Endpoint (com.amazonaws.us-west-2.secretsmanager): InvalidParameter: Subnet IDs are only supported for Interface and GatewayLoadBalancer type VPC Endpoints.
│       status code: 400, request id: c3858cb1-8278-4dea-a6d2-177948dcf477
│
│   with module.vpc.aws_vpc_endpoint.secrets_manager,
│   on ..\..\modules\vpc\endpoints.tf line 3, in resource "aws_vpc_endpoint" "secrets_manager":
│    3: resource "aws_vpc_endpoint" "secrets_manager" {
```

### Reproduction Steps

Run through the default example

### Version used

latest

### Environment details (OS name and version, etc.)

windows 10

**Comment by ulises-jeremias** [comment]
hey! @synthKyel thanks for creating this issue! for now I decided to remove the creation of the endpoint from the boilerplate just to unblock others to use this boilerplate but will make the needed changes on other Pull Request to let you create the VPC Endpoint for Secrets Manager using this boilerplate 😊

**Comment by ulises-jeremias** [comment]
@synthKyel this issue is solved in the main branch. We added another module to handle the creation of vpc endpoints!
